### ISSUE TITLE
Layout improvement

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/EltonCustodioPaycheck#2]
This layout can be improved.

![image](https://cloud.githubusercontent.com/assets/5324414/10748349/55ff39fe-7c46-11e5-93a6-e5cd23752739.png)

**Comment by EltonCustodio** [comment]
In firefox got better.
![capturar](https://cloud.githubusercontent.com/assets/10840245/10772093/67d8da96-7cdb-11e5-98c7-53673d5d98a2.PNG)
I erred in not test in chrome.

**Comment by edysegura** [comment]
Awesome!!!!
